name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Testing on ${{matrix.os}} and Node ${{matrix.node_version}}
    timeout-minutes: 10
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [10, 14]
        graphql_version: [14, 15]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node ${{matrix.node_version}}
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node_version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache Yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install GraphQL v${{matrix.graphql_version}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version}}
      - name: Install Dependencies using Yarn
        run: yarn install && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v1
        with:
          path: .cache/jest
          key: ${{ runner.os }}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-jest-
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --logHeapUsage
